# BEGINNER VERSION - Very Simple CI/CD
# This just runs your tests automatically when you push code

name: 🔥 Simple Test Runner (Beginner)

# When to run? When you push code to main branch
on:
  push:
    branches: [ main ]

jobs:
  run-tests:
    runs-on: ubuntu-latest  # Use Ubuntu computer
    
    steps:
    # 1. Get your code
    - uses: actions/checkout@v4
    
    # 2. Install Python
    - uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    # 3. Install Chrome
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    # 4. Install your packages
    - name: Install packages
      run: |
        pip install pytest selenium allure-pytest
    
    # 5. Run your tests (headless = no browser window)
    - name: Run tests
      run: |
        pytest tests/ --env=prod --headless -v
    
    # 6. Tell you if it worked or failed
    - name: Tests completed
      if: success()
      run: echo "✅ All tests passed!"
    
    - name: Tests failed
      if: failure()
      run: echo "❌ Some tests failed!"
